### ISSUE TITLE
kubermatic-api crashes with concurrent map writes

### ISSUE THREAD

**Issue by embik** [kubermatic/dashboard#5660]
### What happened

On the v2.22.0-alpha.0 QA environment, kubermatic-api seemingly crashes randomly (?) with the Go stack trace below. This happened in both Pods, so I assume it's reproducible.

```
fatal error: concurrent map writes

goroutine 467 [running]:
k8s.io/apimachinery/pkg/conversion.ConversionFuncs.AddUntyped({0x40ab280?}, {0x40ab280, 0xc001b90a00}, {0x40ab280, 0xc001b90a00}, 0x4913348)
	k8s.io/apimachinery@v0.26.1/pkg/conversion/converter.go:124 +0x169
k8s.io/apimachinery/pkg/conversion.(*Converter).RegisterGeneratedUntypedConversionFunc(...)
	k8s.io/apimachinery@v0.26.1/pkg/conversion/converter.go:174
k8s.io/apimachinery/pkg/runtime.(*Scheme).AddGeneratedConversionFunc(...)
	k8s.io/apimachinery@v0.26.1/pkg/runtime/scheme.go:325
k8s.io/apimachinery/pkg/runtime.(*Scheme).AddKnownTypeWithName(0xc00019b8f0, {{0x4768561, 0x18}, {0x472868b, 0xa}, {0x4728519, 0xa}}, {0x4e6acc0?, 0xc001b90a00})
	k8s.io/apimachinery@v0.26.1/pkg/runtime/scheme.go:186 +0x7b0
k8s.io/apimachinery/pkg/apis/meta/v1.AddToGroupVersion(0xc00019b8f0?, {{0x4768561?, 0xc0004fb500?}, {0x4724406?, 0x471a20b?}})
	k8s.io/apimachinery@v0.26.1/pkg/apis/meta/v1/register.go:68 +0x1d3
kubevirt.io/api/instancetype/v1alpha1.addKnownTypes(0xc003536730?)
	kubevirt.io/api@v0.58.0/instancetype/v1alpha1/register.go:62 +0x20b
k8s.io/apimachinery/pkg/runtime.(*SchemeBuilder).AddToScheme(0x4e7ed00?, 0xc003536730?)
	k8s.io/apimachinery@v0.26.1/pkg/runtime/scheme_builder.go:29 +0x5b
k8c.io/dashboard/v2/pkg/provider/cloud/kubevirt.newClient({0xc00068e000, 0x1d88}, {{0x0, {0x0, 0x0}, {0x0, 0x0}}, {0x0, 0x0, 0x0}, ...})
	k8c.io/dashboard/v2/pkg/provider/cloud/kubevirt/client.go:77 +0x1e7
k8c.io/dashboard/v2/pkg/provider/cloud/kubevirt.NewClient({0xc00068e000?, 0x0?}, {{0x0, {0x0, 0x0}, {0x0, 0x0}}, {0x0, 0x0, 0x0}, ...})
	k8c.io/dashboard/v2/pkg/provider/cloud/kubevirt/client.go:90 +0x4e
k8c.io/dashboard/v2/pkg/handler/common/provider.KubeVirtStorageClasses({0x4e822e8, 0xc002fdf500}, {0xc00068e000?, 0xc002fdf500?})
	k8c.io/dashboard/v2/pkg/handler/common/provider/kubevirt.go:104 +0x50
k8c.io/dashboard/v2/pkg/handler/common/provider.KubeVirtStorageClassesWithClusterCredentialsEndpoint({0x4e822e8, 0xc002fdf500}, 0xc0016ceb78?, {0x4e85420?, 0xc0002ccdc8?}, {0x4e73810?, 0xc000777650?}, {0xc0021215d5?, 0x4b4e26?}, {0xc0021215e9, ...})
	k8c.io/dashboard/v2/pkg/handler/common/provider/kubevirt.go:119 +0xae
k8c.io/dashboard/v2/pkg/handler/v2/provider.KubeVirtStorageClassesWithClusterCredentialsEndpoint.func1({0x4e822e8?, 0xc002fdf500?}, {0x4176a60?, 0xc0020407a0?})
	k8c.io/dashboard/v2/pkg/handler/v2/provider/kubevirt.go:241 +0x89
k8c.io/dashboard/v2/pkg/handler/middleware.SetPrivilegedClusterProvider.func1.1({0x4e822e8?, 0xc00206a000?}, {0x4176a60, 0xc0020407a0})
	k8c.io/dashboard/v2/pkg/handler/middleware/middleware.go:169 +0xf7
k8c.io/dashboard/v2/pkg/handler/middleware.SetClusterProvider.func1.1({0x4e822e8?, 0xc00284a270?}, {0x4176a60, 0xc0020407a0})
	k8c.io/dashboard/v2/pkg/handler/middleware/middleware.go:152 +0x87
k8c.io/dashboard/v2/pkg/handler/middleware.UserSaver.func1.1({0x4e822e8, 0xc00284a210}, {0x4176a60, 0xc0020407a0})
	k8c.io/dashboard/v2/pkg/handler/middleware/middleware.go:208 +0x63c
k8c.io/dashboard/v2/pkg/handler/middleware.TokenVerifier.func1.1({0x4e822e8, 0xc002557e60}, {0x4176a60, 0xc0020407a0})
	k8c.io/dashboard/v2/pkg/handler/middleware/middleware.go:306 +0x765
github.com/go-kit/kit/transport/http.Server.ServeHTTP({0xc001599a70, 0x4912618, 0x4911c50, {0xc001597280, 0x3, 0x4}, {0x0, 0x0, 0x0}, 0x4911c58, ...}, ...)
	github.com/go-kit/kit@v0.12.0/transport/http/server.go:121 +0x35b
main.setSecureHeaders.func1({0x7fee4c309200, 0xc002464410}, 0xc002557e00?)
	k8c.io/dashboard/v2/cmd/kubermatic-api/main.go:663 +0x305
net/http.HandlerFunc.ServeHTTP(0xc0022f5200?, {0x7fee4c309200?, 0xc002464410?}, 0x0?)
	net/http/server.go:2109 +0x2f
github.com/gorilla/mux.(*Router).ServeHTTP(0xc00026ec00, {0x7fee4c309200, 0xc002464410}, 0xc00215bd00)
	github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1({0x4e817f0?, 0xc00392fec0?}, 0xc00215bd00)
	github.com/prometheus/client_golang@v1.14.0/prometheus/promhttp/instrument_server.go:146 +0xb8
net/http.HandlerFunc.ServeHTTP(...)
	net/http/server.go:2109
main.instrumentHandler.func1({0x4e817f0, 0xc00392fec0}, 0xc00215bd00)
	k8c.io/dashboard/v2/cmd/kubermatic-api/metrics.go:65 +0xb0
net/http.HandlerFunc.ServeHTTP(0x4e80110?, {0x4e817f0?, 0xc00392fec0?}, 0x702d5f?)
	net/http/server.go:2109 +0x2f
github.com/gorilla/handlers.loggingHandler.ServeHTTP({{0x4e43120, 0xc000124008}, {0x4e45ec0, 0xc001bf2ec0}, 0xc001bdd320}, {0x4e80110, 0xc002434ee0}, 0xc00215bd00)
	github.com/gorilla/handlers@v1.5.1/logging.go:47 +0xef
net/http.serverHandler.ServeHTTP({0xc001b7be90?}, {0x4e80110, 0xc002434ee0}, 0xc00215bd00)
	net/http/server.go:2947 +0x30c
net/http.(*conn).serve(0xc001f38be0, {0x4e822e8, 0xc001bedd10})
	net/http/server.go:1991 +0x607
created by net/http.(*Server).Serve
	net/http/server.go:3102 +0x4db
```

This takes the API offline for a couple of seconds.

### Expected behavior

The API doesn't crash.

### Environment
- UI Version: v2.22.0-alpha.0
- API Version: v2.22.0-alpha.0
- Domain: n/a
- Others: n/a

### Current workaround

None known.

### Affected user persona

A KKP end user.

### Business goal to be improved

Reliability of our API.

### Metric to be improved

Reliability of our API.

**Comment by ahmadhamzh** [comment]
@embik i think it's sig/api right ?

**Comment by embik** [comment]
@ahmadhamzh correct, sorry for the confusion.
